---
repos:
    - repo: local
      hooks:
          - id: generateDoc
            name: generateDoc
            entry: ./warnings-ng/convertersSamples.sh
            language: script
            files: warnings-ng/lintLogsSamples/.*\.(json|txt)$
            pass_filenames: false
            stages: [commit]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-ast
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: end-of-file-fixer
            exclude: ^doc/
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-xml
          - id: check-yaml
          - id: forbid-new-submodules
          - id: check-json
            exclude: ^.vscode/.*$

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shfmt

    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.8.1
      hooks:
          - id: markdownlint-cli2
            args: [--fix]

    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.9.0
      hooks:
          - id: shellcheck

    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
          - id: hadolint-docker
            types: [file]
            files: Dockerfile.*

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
